machine:
  kubelet:
    extraMounts:
      - destination: /var/openebs/local
        type: bind
        source: /var/openebs/local
        options:
          - bind
          - rshared
          - rw
  sysctls:
    vm.nr_hugepages: "1024"
  disks:
    - device: /dev/nvme0n1
      partitions:
        - mountpoint: /var/openebs/local