# Base Configuration
ipam:
  mode: kubernetes

kubeProxyReplacement: true
k8sServiceHost: "localhost"
k8sServicePort: 7445

# Routing Configuration
routing:
  mode: "native"

# CNI Configuration
cni:
  exclusive: true
  install: true
  chainingMode: none

operator:
  replicas: 1
  rolloutPods: true

# Security Context
securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

# Dual-stack Configuration
ipv4:
  enabled: true

ipv6:
  enabled: true
  nativeRoutingCIDR: "fd00:10:244::/56"

dualStack:
  enabled: true

# Node Configuration
nodePort:
  enabled: true
  enableIPv6: true

# BPF and Masquerading
bpf:
  masquerade: true
  hostLegacyRouting: false

# Masquerading
enableIPv4Masquerade: true
enableIPv6Masquerade: true

# Tolerations
tolerations:
  - operator: Exists

# Monitoring
monitor:
  enabled: true

# Debug
debug:
  enabled: true
  verbose: "flow"